create table BENEFIT_PACKAGE
(
    ID          INTEGER AUTO_INCREMENT,
    NAME        CHARACTER VARYING(255),
    DESCRIPTION CHARACTER VARYING(255),
    AMOUNT      FLOAT,
    CURRENCY    CHARACTER VARYING(255),
    constraint PK
        primary key (ID)
);

create table PERSON
(
    ID                      INTEGER AUTO_INCREMENT,
    PERSONAL_ID_CODE        CHARACTER VARYING(255),
    FIRST_NAME              CHARACTER VARYING(255),
    LAST_NAME               CHARACTER VARYING(255),
    EMAIL                   CHARACTER VARYING(255),
    DATE_OF_BIRTH           CHARACTER VARYING(255),
    REGION                  CHARACTER VARYING(255),
    HOME_ADDRESS            CHARACTER VARYING(255),
    PHONE_NUMBER            CHARACTER VARYING(255),
    OCCUPATION              CHARACTER VARYING(255),
    MUNICIPALITY            CHARACTER VARYING(255),
    ZIP_CODE                CHARACTER VARYING(255),
    constraint ID
        primary key (ID),
    UNIQUE(PERSONAL_ID_CODE)
);